### ISSUE TITLE
Map out the current flows related to account creation and org creation, identify pain points

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/user-experience#1]
[Figma file](https://www.figma.com/file/bKHwc5l4LlxlpddcAEYUpF/Account-%26-Org-Creation-Flows?node-id=0%3A1)
### Pain Points 
- Home page primary buttons prioritize flows through docs and caters to independent usage of the CLI rather than SaaS account creation
- "Sign In" only on homepage nav, no "Sign up." This is the only pathway to account creation
- First mention of the Pulumi service in the "Getting Started" flow comes 3-4 clicks deep (see related issue below)
- Sign-up link on sign-in page low hierarchy, tertiary link
- Sign-in and sign-up need language differentiation
- No visual changes when toggling from sign-in to sign-up. Difficult to tell user has moved pages (see related issue below)
-  "New organization" option hidden until clicked on Service dashboard
- No copy related to the Team plan when adding an org from the Service dashboard
- Query parameter dropped when starting a free trial from the pricing page and needing to sign up (see related issue below)

### Related Issues
[Improve sign in/sign up pages](https://github.com/pulumi/pulumi-service/issues/6596)
[Sign Up page ignores query parameter for Free Trial](https://github.com/pulumi/pulumi-service/issues/8001)
[Get Started should offer a clearer pathway to creating a service account](https://github.com/pulumi/pulumi-hugo/issues/994)

**Comment by susanev** [comment]
@anita-trimbur its good that you have the figma file in this, but can you also add a comment that describes the pain points you identified and also link to the issues you created as a result of this work? then we can close this out.
