### ISSUE TITLE
Toggle color of background dots on Create an Account page

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/user-experience#17]
Color of background dots should change when toggling between Sign In and Create an Account to visually cue users when the page has changed. 

## Hex Codes for Create an Account
Top right dot: **#8A3391**
Bottom left dot: **# F6B73**

![4 Create Account with Email (1)](https://user-images.githubusercontent.com/97129308/153671343-395e4ca0-6619-4768-bd0d-ce007b349626.png)
![2 Sign-in with Email](https://user-images.githubusercontent.com/97129308/153671423-36e1110a-c784-4b36-9538-ecbc972549be.png)

**Comment by susanev** [comment]
@anita-trimbur @kimberleyamackenzie is there anything we can change in the future to make it easier to catch these things before we ship?

**Comment by anita-trimbur** [comment]
@susanev This was my bad, Kimberley and I had a 1:1 where we went over any discrepancies and I just didn't catch this until I was prepping for TGIF last week. I can make a better effort to call out these easily missable type things in my handoff notes.

**Comment by susanev** [comment]
ah sry, was not trying to blame anyone. but if there's something we can work into our process to reduce this happening in the future id love to do it!
