### ISSUE TITLE
Instrument the Service dashboard in preparation for new experience

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/user-experience#31]
I touched base with @kimberleyamackenzie last week to determine whether we had instrumented any part of the Service dashboards in Mixpanel and we didn't find anything. In preparation for the new dashboard designs, it'd be great to establish a baseline for how our users are interacting with the current dashboard with some usage data.

- Do users customize their dashboard? Do they achieve this through the "Customize Dashboard" dropdown, or by hiding the cards from the meatball menus? Which cards are hidden most often?
- How long do users typically spend on their dashboards? Are they immediately clicking onto a different page? If so, where are they going?
- Are users making use of the Get Started card? How often do users click through the steps? Are the checkboxes being used?
- Do users follow the links on the Latest Stack Updates card? Or do they just navigate to the stacks they're looking for manually?
- How often do individual accounts click the "Create Organization" button? How often do organization accounts click "Invite members"?

**Comment by kimberleyamackenzie** [comment]
New instrumentation:

- [x] On select of "Customize Dashboard"
- [x] On individual selects of customize dashboard checks, with card names
- [x] On select of "Hide" card in the meatball menu, with card name
- [x] Get started card interactions - next, previous buttons, checkboxes.
- [x] Create org button, with org/personal data
- [x] Invite members button

We already have:
1. Nav from dashboard -> elsewhere
2. Timing how long folks are on the dashboard.  Mixpanel keeps some data for us about this, I'll just have to figure out the best way to write a query to match all possible dashboard URLs.
3. Following links on latest stack updates card - we can get this with a query that tracks dashboard -> stack navigation

**Comment by kimberleyamackenzie** [comment]
The new analytics needed here are added in https://github.com/pulumi/pulumi-service/pull/8881.  Once that PR goes to prod and we have some data, I'll come back to update this ticket with links to all the mixpanel queries to answer each question.

**Comment by kimberleyamackenzie** [comment]
The PR has been merged + released, and should be released with https://github.com/pulumi/pulumi-service/pull/8886 this morning.  Moving back into development so I can add links to the appropriate queries here once we have some data in Mixpanel.

**Comment by kimberleyamackenzie** [comment]
Queries:


- [x] On select of "Customize Dashboard" menu: https://mixpanel.com/s/7ifA7
- [x] In the "Customize Dashboard" menu, checking to show an individual card: https://mixpanel.com/s/1sMALk
- [x] In the "Customize Dashboard" menu, checking to remove/hide an individual card: https://mixpanel.com/s/2Pv7y
- [x] On select of "Hide" card in the meatball menu for an individual card: https://mixpanel.com/s/14nLya
- [x] Get started card interactions - next + previous buttons, checkboxes, help dialog, cloud + language selection changes: https://mixpanel.com/s/2I3fOe
- [x] On select of the "Create org" button: https://mixpanel.com/s/2h3EzH
- [x] On select of the "Invite members" button: https://mixpanel.com/s/laiT8

For the 3 items that related to navigation from the dashboard - This data is a little tedious to get (because the URLs are unique for every org, since its their org name), I need to investigate an easier way to get at this for us with Mixpanel.  We have the data, I just need to poke around and figure out how to consume it.

**Comment by kimberleyamackenzie** [comment]
Okay, I think I have something for the navigation related items.  The regex I used may need a little refining for some non-alphabetic characters in org names, but it's a pretty good approximation for now and I can tweak it when my brain can handle more regex-ing on Tuesday :)

- [ ] Nav from dashboard -> elsewhere: https://mixpanel.com/s/3NoVAQ
- [ ] Time spent on the dashboard: https://mixpanel.com/s/1sxHNn

**Comment by anita-trimbur** [comment]
Some preliminary statistics for gathered from this instrumentation.

### Time Spent on Dashboard
Nearly half of all users who land on the dashboard page click away in ten seconds or less.
![Seconds Screenshot](https://user-images.githubusercontent.com/97129308/171446924-8252204a-79ee-490a-99e8-c4d9c540468a.png)
Over 75% of all users who land on the dashboard page click away in under a minute.
![Minutes Screenshot](https://user-images.githubusercontent.com/97129308/171446966-a5d738ed-847e-4441-b8e1-db7152b406a8.png)

### Weekly Dashboard Views
Graph shows number of unique dashboard views during a work week period in May. The average number of unique dashboard views on May weekdays is 725.4.
![Screen Shot 2022-05-31 at 4 48 1](https://user-images.githubusercontent.com/97129308/171447066-cb865456-e771-43a9-8d62-19b21b361186.png)

### Funnel From Dashboard to Projects
43.64% of all sessions result in users navigating from the dashboard to the projects page in an average of 174 seconds.
![Screen Shot 2022-05-31 at 5 13 1](https://user-images.githubusercontent.com/97129308/171447142-c882aa03-38a3-4ce0-9ad1-62d83526c1b6.png)

### Dashboard Actions
Data collection began on May 26th. We will not account for averages until at least two work weeks’ worth of data has been captured. 

#### Invite Members
Current day-to-day data suggests that the invite members button is not a frequently taken action from the dashboard. On May 31st, 801 unique users visited the dashboard and only 5 instances of the Invite Members button selection were recorded.

#### Create Organization
Current day-to-day data suggests that the create organization button is not a frequently taken action from the dashboard. On May 31st, 801 unique users visited the dashboard and only 8 instances of the Create Organization button selection were recorded.

#### Show / Hide Cards 
Current day-to-day data suggests that the show / hide actions are not frequently taken in the dashboard. The maximum unique interactions in any given day has not exceeded 2 for showing or hiding any card either via the meatball menu or the Customize Dashboard dropdown. 

#### Get Started
Since data collection began on May 26th, more unique users have taken action inside the Get Started card than have taken action on any other card in this list. Of the actions within Get Started, the least frequently taken is the checkbox toggle.

![Screen Shot 2022-05-31 at 5 29 1](https://user-images.githubusercontent.com/97129308/171447442-6d2d4f19-460b-4b93-9828-955791213e51.png)
