### ISSUE TITLE
cleanup for docs/registry search work

### ISSUE THREAD

**Issue by susanev** [pulumi/user-experience#32]
this is a parent issue for a few issues...

- [x] https://github.com/pulumi/theme/issues/107
- [x] https://github.com/pulumi/pulumi-hugo/issues/1344
- [x] https://github.com/pulumi/registry/issues/835
- [x] https://github.com/pulumi/theme/issues/107

**Comment by kimberleyamackenzie** [comment]
Leaving some notes for my future post-PTO self about the status of this work:
- Changes that address all the items in the linked tickets above are completed in Registry, Docs, and Theme.  Links to branches below. Mostly ready for PR, just need to iron out two items below:
- Before PRing:
- [ ] Get UX team feedback about header - dots, height.  If we go dots, fix overlay to cover the top row of dots.
- [ ] Update the go mods to all point to the right things in each PR for each repo

https://github.com/pulumi/pulumi-hugo/tree/km/nav-updates
https://github.com/pulumi/theme/tree/km/nav-updates
https://github.com/pulumi/registry/tree/km/nav-updates
