### ISSUE TITLE
Audit the current Pulumi Service dashboard and aggregate existing pain points

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/user-experience#33]
## Overview

In preparation for the upcoming dashboard redesigns, we need to audit our existing dashboard and identify key areas of improvement. 

### Individual Accounts

![Individuals (1)](https://user-images.githubusercontent.com/97129308/163829033-ad2dffa3-53c3-4dd9-8b28-baa5ec105cc3.png)

Individual accounts can access a maximum of 5 cards on their dashboards: 

1. **People** is a button that takes the user to the Create an Organization page
2. **Get Started** is a stepper with one-click copy commands, links to our Docs, and a checklist intended to guide users through their first experience with the CLI
3. **Learn** is a checklist intended to guide users through their early experience with the CLI
4. **Latest Stack Updates** is a list that links to the most recently updated stacks 
5. **Resource Count Over Time** is a graph with togglable time range and a download option intended to bring visibility to users' resource usage

### Organization Accounts

![Orgs (1)](https://user-images.githubusercontent.com/97129308/163829043-ca3c2d12-b64a-443f-9964-66ea4796f4af.png)

Org accounts can access a maximum of 5 cards on their dashboards: 

1. **People** is a button that takes the user to the Members page to invite additional team members
2. **Learn** is a checklist intended to guide users through their early experience with the CLI
3. **CI/CD Integrations** is a button that takes the user to the Settings > Integrations page
4. **Latest Stack Updates** is a list that links to the most recently updated stacks 
5. **Resource Count Over Time** is a graph with togglable time range and a download option intended to bring visibility to users' resource usage

## Known Pain Points
- No Get Started card is included on org accounts because org members have varying levels of experience and could be arriving from several different pathways
- Card organization can result in unbalanced columns, or alternatively force equal card heights
- New users don't have any data to populate the Resource Count or the Latest Stack Update cards
- The Learn and Get Started card have redundant information
- The CI/CD card for orgs functions mostly as a feature advertisement 
- There is no useful empty state for when a user hides all their cards

## Analysis

We have the means to **surface more insights** to both individuals and organizations about their Pulumi usage that will help increase their data awareness. The Resource Count card is arguably the highest value card we have now, and it would helpful to not only expand its functionality, but to introduce similar cards for performance tracking.

There is **not enough habitual interaction with the dashboard** to make for a meaningful experience. The majority of dashboard cards are targeted for users just starting out with Pulumi: Learn, Get Started, and even the People cards are most useful to newer users. Recently, a user wrote in the community Slack that "the 'Dashboard' is completely useless in most cases." It's understandable that once a user is familiarized with the CLI and has established a workflow -- either as an individual or within an org -- that they have limited use cases for the dashboard. We need encourage users to return to the dashboard and, more broadly, login to the Service regularly to engage in habitual task flows.

The majority of **card actions take users away from the dashboard**. Many of the interactions built into our current cards involve clicking a link that either 1) leads elsewhere in the Service or 2) completely removes the user from the Service and into the Docs. Ideally, we need to introduce cards that function wholly inside the dashboard. This will reinforce the value of the Service and address the need for habitual interaction described above.

**Comment by susanev** [comment]
closing this as complete
