### ISSUE TITLE
Explore dashboard experiences and best practices

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/user-experience#34]
## Overview

In preparation for the upcoming dashboard redesigns, we need to explore other dashboard experiences in adjacent problem spaces and beyond, as well as research best practices.

### Datadog
![Datadog Dashboard 1](https://user-images.githubusercontent.com/97129308/163860595-a9cc842f-6176-4cbf-897e-6c91aa6a6171.png)
![Datadog Dashboard 2](https://user-images.githubusercontent.com/97129308/163860598-36b2b9c0-3b6e-47df-919a-3639f29c0ce0.png)
![Datadog Dashboard 3](https://user-images.githubusercontent.com/97129308/163860601-54885c32-9665-4233-8890-7ac5047faade.png)

- Some dashboard layouts have the same balancing problems we do, where many cards align to one side of the page.
- Customizable widgets allow users to track the precise data they're interested in.
- Offers multiple options depending on the level of control the user wants to have over their dashboard: auto-layout, snap to place, and an infinite canvas
- Some dashboard cards include notification tracking, live monitor, custom graphs, and annotations
- Empty states are not particularly useful.

### Sentry.io

![Sentry io Dashboard 1](https://user-images.githubusercontent.com/97129308/163862512-e97fb945-3fc7-4a38-a68f-a62d6fc81ce9.png)
![Sentry io Dashboard 2](https://user-images.githubusercontent.com/97129308/163862519-720b0d7b-dcad-40eb-b1c0-45d24c2a0fc8.png)
![Sentry io Dashboard 3](https://user-images.githubusercontent.com/97129308/163862522-dc95ae66-b8aa-42d8-a833-f93b085c72e9.png)

- Offers different templates depending on the user's area of focus.
- Templates can be previewed, but the previews don't include demo content, nor are the empty states aren't particularly useful
- Does not adapt well to smaller screen widths: text cuts off everywhere and horizontal scrollbars are introduced
- Widgets can be edited. Editing menu provides a link to docs.
- All widgets can be expanded into a larger view.

### Fathom Analytics

![Fathom Analytics Dashboard](https://user-images.githubusercontent.com/97129308/163864600-c68cf756-3f66-4415-aeea-999c77c4d66d.png)

- Shows a preview dashboard populated with information.
- Top bar is hierarchically prominent, shows the most important metrics.
- Search function inside cards.
- Time range togglable across cards.

### GKE

![GKE Dashboard 2](https://user-images.githubusercontent.com/97129308/163864960-a055515b-482a-4491-853b-08eddde6293b.png)

- Graphs are hierarchically the most prominent component of the dashboard.
- Cards are collapsible.
- Information dense cards are filterable.

**Comment by anita-trimbur** [comment]
## Dashboard Types

Dashboards roughly fit into three major subtypes

1. **Operational dashboards** are best suited to practitioners who want daily performance insights. These dashboards are designed to be integrated into a habitual workflow.
2. **Strategic dashboards** are best suited to administrators who want updates on KPIs and high-level performance summaries. Information helps inform goal-setting.
3. **Analytical dashboards** are best suited to administrators or analysts who want deep insight into trends over time. 

## Best Practices

Providing users with an information dashboard does not ensure knowledge generation on its own. The utility of the dashboard is dependent on how well it caters to the end-user. Some considerations include:

- User preference
- Input data
- User ability
- User role

Users often need different visual metaphors or compositions to understand the same dataset. An ill-suited visual metaphor could further lead to mistakes in interpreting data.

When designing dashboards, it’s imperative to abstract data visualization tasks. Ask questions like “What does the user want to know or discover through this visualization?” Ultimately tasks hold richer semantic value than a single event (e.g. a click). Consider three levels of actions:

1. Analysis
2. Search
3. Query

[Article link](https://www.mdpi.com/2076-3417/10/7/2306/htm)

**Comment by susanev** [comment]
closing this as complete
