### ISSUE TITLE
Plan and conduct user interviews to gather dashboard requirements

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/user-experience#35]
## Overview

In preparation for the upcoming dashboard redesigns, we need to clarify how our users overview their operations and uncover key areas where users have an obstructed line of sight. User data will inform what content we surface on the dashboards. We need to understand what different user types are looking for so we can cater to their specific needs whether they’re operational, analytical, or strategic in nature. Any decisions will be predicated on alleviating friction for our users and anticipating, then exceeding, their wants and needs.

## Key Research Questions

- What kind of insights are users missing from their Pulumi usage? 
- What information is most valuable to users in different roles?
- What pain points exist when managing daily operations?

## Participants
Participants are volunteers from Pulumi’s Community Slack channel. They vary in experience-level, account type, and span a range of role titles including: software engineer, dev ops engineer, and developer advocate. Participants are predominantly men.

## References
[Full interview script on Dovetail](https://dovetailapp.com/data/5eK72jzEKn6BEHp7Vm8TIY)
[Research Insights](https://dovetailapp.com/projects/2eUsktgnFgUlHO1s1wN3dL/v/1HLJzmwi2CTVGbIHe0mwyn/present)
[Report](https://docs.google.com/document/d/1ypnySE4l0jttiot2WhF-EhnKHf68HhvIHy4FD5wrcfA/edit)

## Details
11 user interviews to be conducted between April 25th - April 29th. Interviews will run between 15 - 30 minutes and will be attended by @anita-trimbur and @susanev.

**Comment by susanev** [comment]
this has been completed
