### ISSUE TITLE
Iterate in low fidelity for Service dashboard UI designs

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/user-experience#39]
### [Figma File](https://www.figma.com/file/2Jht0rAeeAkOFDHVrzfXKj/Service-Dashboard?node-id=102%3A3)

This lo-fi iteration subdivides the dashboard into tailored "views." The Operational view is intended to serve Pulumi practitioners who come to the Service to perform routine operations or maintenance. It is information dense and intended to aid users in quickly finding and navigating to pages of interest. This Analytical view represents a high-level or “big picture” overview of Pulumi operations. It is heavy on visual data and is intended to be consumed by people managers, project leads, admins, or analysts.

Our user research findings highlight the spectrum of user types consuming information in the Service. Separating out dashboard views allows users to consume the information most relevant to their role without obscuring nonessential information. 

Additional functionality includes:
- Draggable cards for custom ordering
- Collapsible card
- Individual card settings for visualization visibility

#### Operational Cards
- **Latest Stack Updates.** Some modifications to our existing Latest Stack Activity card. Represents activity in a timeline view and exposes additional info like stack creations and deletions.
- **Favorite Stacks.** Reinforces favoriting functionality to be introduced in the updated navigation. Allows users to favorite stacks for quick access after login.
- **Failed Updates.** Helps users quickly jump into error recovery workflows when they log in to the service. Updates can be manually cleared or will auto-clear once the update succeeds. Button takes users to the details page of each operation.
- **CLI Commands.** Customizable list of one-click copy CLI commands. Common commands are listed quick reference, and users can minimize any commands that aren’t helpful.
- **Getting Started.** Styling modifications to our existing card.

![Image](https://user-images.githubusercontent.com/97129308/171446401-9a4317d5-a2be-4cfd-a445-462b308b0d78.png)

#### Analytical Cards
**Quick Stats.** Members, credits, total stacks, total resources, successful updates in x time range.
**Weekly Overview.** Takes inspiration from GitHub’s “Pulse.” Gives a weekly overview of who contributed to Pulumi operations as well as a cumulative count of additions and deletions across the org. Card also includes a timeline of changes during the week with a button to jump to the details page of each operation.
- **Resource Breakdowns**
    - _Cloud Provider._ Pie-chart grid breaking down resources by cloud provider.
    - _Instance Size._ Pie-chart grid breaking down resources by instance size. Charts are rendered per cloud provider. The user can toggle the visibility of graphs by selecting the gear icon in the bottom right corner of the card. If the account is multi-cloud, the four providers with the most resources are visible by default, and the user can manually toggle the visibility of any additional providers from the card settings.
    -  _Server Region._ Pie-chart grid breaking down resources by server region. Charts are rendered per cloud provider. The user can toggle the visibility of graphs by selecting the gear icon in the bottom right corner of the card. If the account is multi-cloud, the four providers with the most resources are visible by default, and the user can manually toggle the visibility of any additional providers from the card settings.
- **Resource Count Over Time.** Some modifications to our existing Resource Count Over Time card. More information is revealed on hover including % change, # of projects created, # of stacks created, # of stacks deleted, and # of members added. Timescale has also been altered so the x-axis increases in more predictable units. The view can be toggled between a line graph and bar chart representation of data.
- **Members.** Quick view and actions for members management. The card will always show the four most recently added members. If there are pending invites, the bottom half of the card will show when the invite was sent alongside actions to resend or cancel the invitation.

![Image](https://user-images.githubusercontent.com/97129308/171446454-11d0042a-ccf0-4851-9f44-791d8b7acf0b.png)

**Comment by susanev** [comment]
closing this as complete
