### ISSUE TITLE
setup mixpanel dashboard with data about new ux

### ISSUE THREAD

**Issue by susanev** [pulumi/user-experience#41]
setup mixpanel dashboard with data about new ux

**Comment by kimberleyamackenzie** [comment]
Here's a dashboard with some reports: https://mixpanel.com/project/2660889/view/3198281/app/dashboards#id=3672924.  I have hit my max of saved reports, so I have a few more reports to add and I've linked those in Slack for someone else to add so those should get there sometime tomorrow when someone has time.  Putting this "in review" pending reviewing in a team meeting, then will close out.

**Comment by susanev** [comment]
closing as we have a dashboard in place now
